### ISSUE TITLE
Политика конфиденциальности

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.media#370]
Реализовать возможность подтверждения ознакомления с политикой конфиденциальности сайта организации

**Comment by neSpecc** [comment]
- Добавить в базу поле `privacy_policy_url`
- Если оно заполнено, показывать под формой регистрации сообщение "Регистрация означает согласие с <a>политикой конфиденциальности</a>"
- добавить на school332.ru ссылку на политику конфиденциальности
