### ISSUE TITLE
How to run CodeX Media locally without Docker?

### ISSUE THREAD

**Issue by web-xaser** [codex-team/codex.media#462]

**Comment by talyguryn** [comment]
At this time we have no published guide how to run CodeX Media on the production (or local) environment without Docker. you can try to install all dependencies and configure them:

- nginx
- php 5.6 + extensions
- redis
- memcached
- mysql


Follow the [deployment guide](https://github.com/codex-team/codex.media/blob/master/docs/deployment.md) and set up your environment step by step.

---

 :star2: I have a sketch of this guide in the pull request. [check out it](https://github.com/codex-team/codex.media/blob/fixes/docs/production-deployment.md) and give a feedback.

**Comment by web-xaser** [comment]
@talyguryn, error on docker build step:
```
ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint codexmedia_redis_1 (c25e2274c99637c35a4a4347701937f9217edcc92a5c2852944c4604637ac670): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use
ERROR: for memcached  Cannot start service memcached: driver failed programming external connectivity on endpoint codexmedia_memcached_1 (6cde5fd6d3f7ec9e815fdd76811818e8f5bfe68b6d45f016044d92fe2e62b01f): Error starting userland proxy: listen tcp 0.0.0.0:11211: bind: address already in use
ERROR: for mysql  Cannot start service mysql: driver failed programming external connectivity on endpoint codexmedia_mysql_1 (341916d69ae74721a0c43e179db3fcc8e9ab60d3e77886eac73cf41d5f4dbd69): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
```
And error on npm build step:
```
npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build_js"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! codex.media@1.1.0 build_js: `webpack --config js.webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the codex.media@1.1.0 build_js script 'webpack --config js.webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codex.media package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config js.webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codex.media
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codex.media
npm ERR! There is likely additional logging output above.
```

**Comment by talyguryn** [comment]
@web-xaser 

Make sure that these ports are not in use.

`... listen tcp 0.0.0.0:6379: bind: address already in use`
`... listen tcp 0.0.0.0: 11211: bind: address already in use`
`... listen tcp 0.0.0.0: 3306: bind: address already in use`

Try to install the latest Node.js and npm

`npm ERR! node v4.2.6`
`npm ERR! npm  v3.5.2`

**Comment by talyguryn** [comment]
ok, now there is a no way to run it without docker because of compatibility support. but if you want, read [docker-compose.yml](https://github.com/codex-team/codex.media/blob/master/docker-compose.yml) file for dependencies and their settings, [docker/php/Dockerfile](https://github.com/codex-team/codex.media/blob/master/docker/php/Dockerfile) for setting up environment and [codex-media.conf](https://github.com/codex-team/codex.media/blob/master/docker/codex-media.conf) as nginx server's settings
