### ISSUE TITLE
Починить докер

### ISSUE THREAD

**Issue by PolinaShneider** [codex-team/codex.media#463]
![screen shot 2018-11-15 at 22 45 55](https://user-images.githubusercontent.com/15448200/48577463-488d8d00-e928-11e8-8e37-e95a49c55f47.png)

https://stackoverflow.com/questions/43437490/pdo-construct-server-sent-charset-255-unknown-to-the-client-please-rep

**Comment by talyguryn** [comment]
resolved in #464
