### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Butonix** [codex-team/codex.media#468]
Скажите, почему не работает авторизация?
Регистрируюсь, в бд запись появилась, пытаюсь войти, страница обновляется но авторизации не происходит, так же и через вк, все настроил, обновление идет а авторизации нет

**Comment by talyguryn** [comment]
Документация по установке и настройке сайта готовится в реквесте #459.

Я пока не понял суть вопроса. 
> все настроил
> но личного кабинета нет

Сверьтесь с [документацией](https://github.com/codex-team/codex.media/blob/fixes/docs/deployment.md) и уточните проблему.
