### ISSUE TITLE
main.php ссылается на несуществующие .css и .js файлы

### ISSUE THREAD

**Issue by Rosenboum** [codex-team/codex.media#481]
После установки платформы по гайду трекер ошибок показал проблему в данной строке файла */www/application/views/main.php*
`<link rel="stylesheet" type="text/css" media="all" href="/public/build/bundle.css?v=<?= filemtime('public/build/bundle.css'); ?>">`
Как оказалось, папки *build* и соответствующего файла нет вовсе. Аналогичная ситуация с подключением скриптов:
`<script src="/public/build/bundle.js?v=<?= filemtime('public/build/bundle.js'); ?>" onload="codex.init({uploadMaxSize : <?= UPLOAD_MAX_SIZE ?>})"></script>
`
Опытно-дедуктивным путём установил, что ни один из присутствующих в *codex.media* стилей не является правильным

**Comment by eriskhan** [comment]
Смогли как-то решить эту проблему?

**Comment by Rosenboum** [comment]
> 
> 
> Смогли как-то решить эту проблему?

Nope

**Comment by eriskhan** [comment]
Решил проблему, добавив файлы из демки в нужные директории: 
https://school332.ru/public/build/bundle.css?v=1542471917
https://school332.ru/public/build/bundle.js?v=1542471912

**Comment by Butonix** [comment]
> После установки платформы по гайду трекер ошибок показал проблему в данной строке файла _/www/application/views/main.php_
> `<link rel="stylesheet" type="text/css" media="all" href="/public/build/bundle.css?v=<?= filemtime('public/build/bundle.css'); ?>">`
> Как оказалось, папки _build_ и соответствующего файла нет вовсе. Аналогичная ситуация с подключением скриптов:
> `<script src="/public/build/bundle.js?v=<?= filemtime('public/build/bundle.js'); ?>" onload="codex.init({uploadMaxSize : <?= UPLOAD_MAX_SIZE ?>})"></script> `
> Опытно-дедуктивным путём установил, что ни один из присутствующих в _codex.media_ стилей не является правильным

А не судьба выполнить команду yarn build ?

**Comment by talyguryn** [comment]
We have updated project's structure and deploy methods. Read the docs [general-installation.md](https://github.com/codex-team/codex.media/blob/master/docs/general-installation.md)
